### PR TITLE
Allow to use slashes in executed commands if they are not leading slashes

### PR DESCRIPTION
**Pull request by riddle**
This works now:

```
CommandsByConsole:
- sudo %PLAYER_NAME% runalias /toolkit
```

This is still sanitized:

```
CommandsByConsole:
- /gamemode 1 %PLAYER_NAME%
```

### CODE REVIEW

**Comment by riddle** [comment]
The change affects both `CommandsByConsole` and `Commands`.

**Comment by riddle** [comment]
@TH3PF Can we get a yay or nay? :)

**Comment by TH3PF** [comment]
That's a yay :+1:

**Comment by riddle** [comment]
Thanks, appreciate it. :)

**Pull request merged**
